name: Deploy Next.js SSR to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0' # Use LTS for stability

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠️ Build Next.js (standalone)
        run: npm run build

      - name: 🧳 Package standalone output
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp -r public deploy/public || true
          cp package.json deploy/

      - name: 🚀 Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_APP_SERVICE_NAME>
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
